fix(deps): update okhttp monorepo to v5 (major) (#274)
This PR contains the following updates:

| Package | Change | Age | Confidence |
|---|---|---|---|
|
[com.squareup.okhttp3:logging-interceptor](https://square.github.io/okhttp/)
([source](https://redirect.github.com/square/okhttp)) | `4.12.0` ->
`5.1.0` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/com.squareup.okhttp3:logging-interceptor/5.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/com.squareup.okhttp3:logging-interceptor/4.12.0/5.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [com.squareup.okhttp3:okhttp](https://square.github.io/okhttp/)
([source](https://redirect.github.com/square/okhttp)) | `4.12.0` ->
`5.1.0` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/com.squareup.okhttp3:okhttp/5.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/com.squareup.okhttp3:okhttp/4.12.0/5.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

> [!WARNING]
> Some dependencies could not be looked up. Check the Dependency
Dashboard for more information.

---

### Release Notes

<details>
<summary>square/okhttp
(com.squareup.okhttp3:logging-interceptor)</summary>

###
[`v5.1.0`](https://redirect.github.com/square/okhttp/blob/HEAD/CHANGELOG.md#Version-510)

*2025-07-07*

- New: `Response.peekTrailers()`. When we changed `Response.trailers()`
to block instead of
throwing in 5.0.0, we inadvertently removed the ability for callers to
peek the trailers
(by catching the `IllegalStateException` if they weren't available).
This new API restores that
  capability.

- Fix: Don't crash on `trailers()` if the response doesn't have a body.
We broke \[Retrofit] users
who read the trailers on the `raw()` OkHttp response, after its body was
decoded.

###
[`v5.0.0`](https://redirect.github.com/square/okhttp/blob/HEAD/CHANGELOG.md#Version-500)

*2025-07-02*

This is our first stable release of OkHttp since 2023. Here's the
highlights if you're upgrading
from OkHttp 4.x:

**OkHttp is now packaged as separate JVM and Android artifacts.** This
allows us to offer
platform-specific features and optimizations. If your build system
handles \[Gradle module metadata],
this change should be automatic.

**MockWebServer has a new coordinate and package name.** We didn’t like
that our old artifact
depends on JUnit 4 so the new one doesn’t. It also has a better API
built on immutable values. (We
intend to continue publishing the old `okhttp3.mockwebserver` artifact
so there’s no urgency to
migrate.)

| Coordinate | Package Name | Description |
| :----------------------------------------------- |
:-------------------- | :-------------------------------- |
| com.squareup.okhttp3:mockwebserver3:5.0.0 | mockwebserver3 | Core
module. No JUnit dependency! |
| com.squareup.okhttp3:mockwebserver3-junit4:5.0.0 |
mockwebserver3.junit4 | Optional JUnit 4 integration. |
| com.squareup.okhttp3:mockwebserver3-junit5:5.0.0 |
mockwebserver3.junit5 | Optional JUnit 5 integration. |
| com.squareup.okhttp3:mockwebserver:5.0.0 | okhttp3.mockwebserver |
Obsolete. Depends on JUnit 4. |

**OkHttp now supports Happy Eyeballs (\[RFC 8305]\[rfc\_8305]) for
IPv4+IPv6 networks.** It attempts
both IPv6 and IPv4 connections concurrently, keeping whichever connects
first.

**We’ve improved our Kotlin APIs.** You can skip the builder:

```kotlin
val request = Request(
  url = "https://cash.app/".toHttpUrl(),
)
```

**OkHttp now supports \[GraalVM].**

Here’s what has changed since 5.0.0-alpha.17:

- Upgrade: \[Okio 3.15.0]\[okio\_3\_15\_0].
- Upgrade: \[Kotlin 2.2.0]\[kotlin\_2\_2\_0].
- Fix: Don't crash with a `NoSuchMethodError` when using OkHttp with the
Sentry SDK.
- Fix: Retain the query data in the old
`okhttp3.mockwebserver.RecordedRequest.path` property. We
inadvertently changed this behavior when we introduced the
`mockwebserver3` API.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/r0adkll/Campfire).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS4xNy4yIiwidXBkYXRlZEluVmVyIjoiNDEuMTMxLjkiLCJ0YXJnZXRCcmFuY2giOiJtYWluIiwibGFiZWxzIjpbInJlbm92YXRlIl19-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>