Update ktor monorepo to v3.0.3 (#41)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[io.ktor:ktor-serialization-kotlinx-json](https://redirect.github.com/ktorio/ktor)
| `3.0.0` -> `3.0.3` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-serialization-kotlinx-json/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-serialization-kotlinx-json/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-serialization-kotlinx-json/3.0.0/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-serialization-kotlinx-json/3.0.0/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[io.ktor:ktor-client-content-negotiation](https://redirect.github.com/ktorio/ktor)
| `3.0.0` -> `3.0.3` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-client-content-negotiation/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-client-content-negotiation/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-client-content-negotiation/3.0.0/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-client-content-negotiation/3.0.0/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [io.ktor:ktor-client-logging](https://redirect.github.com/ktorio/ktor)
| `3.0.0` -> `3.0.3` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-client-logging/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-client-logging/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-client-logging/3.0.0/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-client-logging/3.0.0/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [io.ktor:ktor-client-auth](https://redirect.github.com/ktorio/ktor) |
`3.0.0` -> `3.0.3` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-client-auth/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-client-auth/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-client-auth/3.0.0/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-client-auth/3.0.0/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [io.ktor:ktor-client-okhttp](https://redirect.github.com/ktorio/ktor)
| `3.0.0` -> `3.0.3` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-client-okhttp/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-client-okhttp/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-client-okhttp/3.0.0/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-client-okhttp/3.0.0/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [io.ktor:ktor-client-darwin](https://redirect.github.com/ktorio/ktor)
| `3.0.0` -> `3.0.3` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-client-darwin/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-client-darwin/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-client-darwin/3.0.0/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-client-darwin/3.0.0/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [io.ktor:ktor-client-core](https://redirect.github.com/ktorio/ktor) |
`3.0.0` -> `3.0.3` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-client-core/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-client-core/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-client-core/3.0.0/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-client-core/3.0.0/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [io.ktor:ktor-http](https://redirect.github.com/ktorio/ktor) | `3.0.0`
-> `3.0.3` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-http/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-http/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-http/3.0.0/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-http/3.0.0/3.0.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>ktorio/ktor (io.ktor:ktor-serialization-kotlinx-json)</summary>

###
[`v3.0.3`](https://redirect.github.com/ktorio/ktor/blob/HEAD/CHANGELOG.md#303)

[Compare
Source](https://redirect.github.com/ktorio/ktor/compare/3.0.2...3.0.3)

> Published 18 December 2024

##### Bugfixes

- "Module not found" errors when executing browserProductionWebpack task
since 3.0.2
([KTOR-7912](https://youtrack.jetbrains.com/issue/KTOR-7912))
- Darwin: "IllegalStateException: Content-Length mismatch" on requesting
gzipped content
([KTOR-7943](https://youtrack.jetbrains.com/issue/KTOR-7943))
- JS/WASM fails with "IllegalStateException: Content-Length mismatch" on
requesting gzipped content
([KTOR-7934](https://youtrack.jetbrains.com/issue/KTOR-7934))
- FormFieldLimit is overwritten by default arg
([KTOR-7946](https://youtrack.jetbrains.com/issue/KTOR-7946))
- A Performance issue reading with ByteReadChannel.readUTF8LineTo
request body
([KTOR-7941](https://youtrack.jetbrains.com/issue/KTOR-7941))
- Installing HttpCache before ContentEncoding prevents response body to
be decoded ([KTOR-7830](https://youtrack.jetbrains.com/issue/KTOR-7830))
- TestApplication.stop() doesn't stop the application anymore
([KTOR-7682](https://youtrack.jetbrains.com/issue/KTOR-7682))
- File is not commited after closing writeChannel() of the file
([KTOR-7845](https://youtrack.jetbrains.com/issue/KTOR-7845))

###
[`v3.0.2`](https://redirect.github.com/ktorio/ktor/blob/HEAD/CHANGELOG.md#302)

[Compare
Source](https://redirect.github.com/ktorio/ktor/compare/3.0.1...3.0.2)

> Published 3 December 2024

##### Bugfixes

- ServletResponseBody is corrupted due to the wrong offset
([KTOR-7904](https://youtrack.jetbrains.com/issue/KTOR-7904))
- File is not commited after closing writeChannel() of the file
([KTOR-7845](https://youtrack.jetbrains.com/issue/KTOR-7845))
- CIO: Response body truncated because read amount of bytes isn't
compared against Content-Length
([KTOR-7828](https://youtrack.jetbrains.com/issue/KTOR-7828))
- HttpCache: IndexOutOfBoundsException on malformed Cache-Control header
([KTOR-7172](https://youtrack.jetbrains.com/issue/KTOR-7172))
- call.respondSource returns empty response but passes in tests
([KTOR-7683](https://youtrack.jetbrains.com/issue/KTOR-7683))
- ByteReadChannel.{readShort/readInt/readLong} leads to infinite loop
when required bytes distributed in flush and read buffers
([KTOR-7746](https://youtrack.jetbrains.com/issue/KTOR-7746))
- Routing: ContentType.match doesn't match wildcard content types
([KTOR-7278](https://youtrack.jetbrains.com/issue/KTOR-7278))
- Connections aren't released properly if there are multiple parallel
connections to the same address
([KTOR-7777](https://youtrack.jetbrains.com/issue/KTOR-7777))
- `FileItem.streamProvider` is deprecated and doesn't have
implementation
([KTOR-7731](https://youtrack.jetbrains.com/issue/KTOR-7731))
- MergedApplicationConfig.toMap replaces nested configs completely
without merging
([KTOR-7008](https://youtrack.jetbrains.com/issue/KTOR-7008))
- Digest Auth: Ktor 3.0.1 uses the wrong "nc" value to calculate digest
([KTOR-7681](https://youtrack.jetbrains.com/issue/KTOR-7681))
- JS: "ReferenceError: require is not defined" when compiling to ES
Module ([KTOR-6158](https://youtrack.jetbrains.com/issue/KTOR-6158))
- Chunked transfer encoding failure not caught with retry
([KTOR-7618](https://youtrack.jetbrains.com/issue/KTOR-7618))
- HttpCookies: IllegalArgumentException when server returns a raw cookie
with not allowed characters
([KTOR-7469](https://youtrack.jetbrains.com/issue/KTOR-7469))
- DefaultRequest: Content-Type header of default request is not
overridable
([KTOR-6946](https://youtrack.jetbrains.com/issue/KTOR-6946))

##### Improvements

- Support binary (Smile) encoding in JacksonConverter
([KTOR-7726](https://youtrack.jetbrains.com/issue/KTOR-7726))
- ServiceLoader.load call is slow on Android
([KTOR-7698](https://youtrack.jetbrains.com/issue/KTOR-7698))

###
[`v3.0.1`](https://redirect.github.com/ktorio/ktor/blob/HEAD/CHANGELOG.md#301)

[Compare
Source](https://redirect.github.com/ktorio/ktor/compare/3.0.0...3.0.1)

> Published 29 October 2024

##### Bugfixes

- Remove space from the default client user agent
([KTOR-7655](https://youtrack.jetbrains.com/issue/KTOR-7655))
- `Url.segments` throws on URLs with root path
([KTOR-7625](https://youtrack.jetbrains.com/issue/KTOR-7625))
- Digest Auth does not implement nc parameter correctly according to RFC
7616 ([KTOR-4318](https://youtrack.jetbrains.com/issue/KTOR-4318))
- about:blank URL should be parsed correctly as about:blank
([KTOR-7410](https://youtrack.jetbrains.com/issue/KTOR-7410))
- ByteReadChannel.{readShort/readInt/readLong} could lead to CPU-bound
indefinite loop since 3.0.0
([KTOR-7571](https://youtrack.jetbrains.com/issue/KTOR-7571))
- CIO: Requests face connection timeouts when executed on the Android
main dispatcher
([KTOR-6803](https://youtrack.jetbrains.com/issue/KTOR-6803))
- receiveMultipart fails with "IOException: Failed to parse multipart"
when content-type is capitalized
([KTOR-7596](https://youtrack.jetbrains.com/issue/KTOR-7596))

##### Improvements

- WebSockets logging: The plugin calls toString() unnecessarily on
transformed response body
([KTOR-7623](https://youtrack.jetbrains.com/issue/KTOR-7623))
- INFO log message with all server interceptors on server startup
([KTOR-7326](https://youtrack.jetbrains.com/issue/KTOR-7326))
- Digest auth: `username` and `cnonce` parameters aren't surrounded with
quotes ([KTOR-7561](https://youtrack.jetbrains.com/issue/KTOR-7561))
- ContentType.fromFilePath for newer file formats HEIC, AVIF, HEIF
([KTOR-7536](https://youtrack.jetbrains.com/issue/KTOR-7536))
- Support missing native targets in ktor-serialization-kotlinx-xml
([KTOR-7583](https://youtrack.jetbrains.com/issue/KTOR-7583))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/r0adkll/Campfire).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xMDcuMCIsInVwZGF0ZWRJblZlciI6IjM5LjEwNy4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6WyJyZW5vdmF0ZSJdfQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>